var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                              xxxx                                              ",
   "                                                                                ",
   "        xxxxxxx                                                  xxxxx          ",
   "        xx!!!xx      xxx                                         x!!!x          ",
   "         xxvxx                          xxxxxx                   xx!xx          ",
   "                                          v                       xvx           ",
   "                               ooo                                              ",
   "                                                                            xx  ",
   "  xx                         xxxxxxx                 o                       x  ",
   "  x  @                       x                                            p  x  ",
   "  xxxxxx     xxxx         xxxx                     xxxxx     ooo             xx ",
   "  xxxxxx     xxxx                                                       e  o  x ",
   "  xx         xxxx   e                                                x        x ",
   "  xx         xxxxx     xxxx   xx     xx     xxxxx          xxxxxxx   xxxxxxxxxx ",
   "             xxxxx!!!!!xxxx   xx!!!!!xx     xxxxx!!!!!!!!!!xxxxxxx   xxxxxxxxxx ",
   "             xx xx!!!!!xxxx   xx!!!!!xx     xx xx!!!!!!!!!!xx   xx   xx         ",
   "             xx xxxxxxxxxxx   xxxxxxxxx     xx xx!!!!!!!!!!xx   xx   xx         ",
   "             xx xxxxxxxxxxx   xxxxxxxxx     xx xxxxxxxxxxxxxx   xx   xx         ",
   "             xx          xx   xx     xx     xx xxxxxxxxxxxxxx                   ",
   "!!!!!!!!!!!!!xx!!!!!!!!!!xx!!!xx!!!!!xx!!!!!x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                         x!!x                                                                ",
   "                                         x!!x                                                                ",
   "                                         x!!x                                                                ",
   "                                         x!!xxxx                                                         ooo ",
   "                                         x!!!!!x                                                             ",
   "                                         xx!!!xx                                                  xx   xxxxxx",
   "                                            |                                                     x!!!!!!!!!!",
   "                                                         oooo          o                          x!!!!!!!!!!",
   "                                                                  xxxx   xxxx          xxx      xxxxxxxxxxx  ",
   "                                                         xxxx     x!!!   !!!x                                ",
   "                                                                  x!!! o !!!x                               x",
   "                                                 ooo              x!!!   !!!x                 xxxxxxxxxx    x",
   "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                          x!!!   !!!x                 xxxxxxxxxx    x",
   "                                       x        xxxx              x!!! o !!!x             oo  xxxxxxxxxx    x",
   "                                       x                          x!!!   !!!x                 xxxxxxxxxx     ",
   "                                       x               oo        =x!!!   !!!x         o  xxxx                ",
   "                                 o                                xxxx o xxxx            xxxx                ",
   "                 xxxxxxxxxx                           xxxx        x                  xxxxxxxx                ",
   "                 x             xxxxx          o                   x                  xxxxxxxx                ",
   "                 x o               x                              x              x   xxxxxxxx                ",
   "        |        x                 x         xxxx                 xe          o  x   xxxxxxxx     o          ",
   "   @             xxxx    xxxx      x                              x              x   xxxxxxxx                ",
   "  xxx      x        x    xx!!!!!!!!x                              xxxxxx   xxxxxxx   xxxxxxxx xxx          xx",
   "  x x      x        xxo   x!!!!!!!!x            xxxx    xx        x                  xxxxxxxx            p  x",
   "!!x x!!!!!!x         x    xxxxxxxxxx     xxx    x!!!!!!!!x        x                  xxxxxxxx            o  x",
   "!!xxx!!!!!!xxx       xx   x                     x!!!!!!!!x        x                  xxxxxxxx               x",
   "!!!!!!!!!!!xxxx  o   x    x      =              x!!!!!!!!x        x                  xxxxxxxx         xxxxxxx",
   "!!!!!!!!!!!xxxxx     x   xx                     x!!!!!!!!x                           xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxx         xxxxxxxxxxxxxx     xxxxxx!!!!!!!x                           xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxx       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!xxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x        x!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",      
   "      v       v     xxxxxxxxxxxxxxxxxxxxxxx                  v                   v        ",  
   "                     xxxxxxxxxxxxxxxxxxxxx    v                                           ",  
   "                      xxxxxxxxxxxxxxxxxx                          v                       ",  
   "         v              xxxxxxxxxxxxxxxx                                                  ",  
   " v                       xxxxxxxxxxxxxxxx          v                                      ",  
   "                      v   xxxxxxxxxxxxxxx                                                 ",  
   "                           xxxxxxxxxxxxxx                             v                   ",  
   "                            xxxxxxxxxxxx                                                  ",  
   "                           xxxxxxxxxxxxx                                                  ",  
   "                          xxxxxxxxxxxxv                                                   ",  
   "                         xxxxxxxxxxxx                       x x                           ",  
   "                        xxxxxxxxxxxx                        x x                           ",  
   "                        xxxxxxxxxxx                         x x                           ",   
   "                        vxxxxxxxxx                 xxxxxxxxxx xxxxxxxxxxx                 ",                                               
   "                          xxxxxxx                  x      o   o   o     x                 ",                                               
   "                           xxxxx     x x           x                   xx                 ",                                                 
   "                            xxx      x x           x   xxxxxxxxxxxxxxxox                  ",                                               
   "             xxxxxxxxxxxxx           x x           x   x             x x                  ",                                               
   "             x           x    xxxxxxxx xxxxxxxx    x   x             xox                  ",
   "           xxx           x    x       o       xxxxxx  xxxx           x x                  ",
   "           x        ooo ex    x                   o      xx          xox                  ",
   "           x             xxxxxx  xxxxxxxxxxx                         x x                  ",
   "           xxx    xxxxxx   o     x         xx xxxxxxxxxx                                  ",
   "             x    x    x         x          x x        xxxx                               ",
   "             x    xx   xxxxxxxxx x          x xxxx                                        ",
   "             x     x           x x               x                                        ",
   "             xx    x           x x               x                                        ",
   "              x    x                             x@                                       ",
   "              x    x                             xxx                                      ",
   "              x   xx                                                                      ",                                               
   "              x   x                                                                       ",
   "              x   x                          xxxxx xxxxx                                  ",
   "              xx  x                          xxxxx xxxxx x                                ",
   "               x  x                          xxxxxoxxxxx                                  ",
   "               x  x                          xxxxx xxxxx                                  ",
   "              xxx x                          xxxxxoxxxxx                                  ",
   "                  o                          x        =xx                                 ",
   "                      x                      xxxxxoxxxxx                                  ",
   "                 xxx  xxx                    xxxxx xxxxx                                  ",
   "               xxx      xxx                  xxxxxoxxxxx                                  ",
   "             xxx          xxx                xxxxx xxxxx x                                ",
   "           xxx|           | xxx              xxxxxoxxxxx                                  ",
   "         xxx        x         xxx            x =       x                                  ",
   "       xxx         xxx          xxx          xxxxxoxxxxx                                  ",
   "     xxx                          xxx        xxxxx xxxxxx                                 ",
   "   xxx      ooo        o   o   o   |xxx      xxxxxoxxxxx                                  ",
   " xxx=                                 xxx    xxxxx xxxxx                                  ",
   " x        xxxxxxx      x   x   x        x    xxxxxoxxxxx                                  ",
   " x!!!!!x  x!!!!!!!!!!!!!!!!x!!!xx  x!!!!x    x      =  x x                                ",
   " xxxxxxx  xxxxxxxxxxxxxxxxxxxxxxx  xxxxxx    xxxxxoxxxxx              p                   ",
   "               v                             xxxxx xxxxx                                  ",
   "                                             xxxxxoxxxxx          x                       ",
   "        xxx              x       xx          xxxxx xxxxxx         x                       ",
   "       xx               xx                   xx|x o x|xxxxxxxxxx  x!!!!!!!!!!x            ",
   "xx                 o   xxx      |                        |  |  |  x!!!!!!!!!!x            ",
   "        ooo          xxxxxxxx       xxx           o               x!!!!!!!!!!x            ",
   "                  xxxxxxxx                                        x!!!!!!!!!!x            ",
   "      xxxxxxx                xx   xx         xxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],


  ["v                                                                                          ",
   "             v                  v                       x        v                  v      ",       
   "                                                        x                                  ",       
   "                                                        x                                  ",       
   "                                                        x                 v                ",       
   "                       v                                x                                  ",       
   "                                                        x                           v      ",       
   "      v                         v                       x                                  ",       
   "                                                        x                                  ",       
   "                                                    @   x                                  ",       
   "             v                                          x                                  ",       
   "                                                        x        v                         ",       
   "                                                    o   x                                  ",       
   "                                                    o   x                                  ",                                                                                                   
   "     o                                              o   x                                  ",
   "                                            xxx     o   x                                  ",                                               
   "  xxxx xxxxxxxxxxxxxxxxxxxxxxxxx             e          x                                  ",                                               
   "xxx        o  o  o  o          x       x           xxx  x                                  ",                                               
   "x                              x      !x                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",                                               
   "x    xxxxxxxxxxxxxxxxxxxx=     x!     !x                x              oooooooooooooooo  x ",                              
   "xxxx       x          ||xx     x!     !xxxxxxxxxxxxxxxxxx                             o  x ",                                            
   "x          x                   x!      x  x             xxxxxxxxxxx   oxxxxxxxxxxxxxxxo  x ", 
   "x                ooooooooo                x            xx            oxx              o  x ",
   "xxxxxxxx  xx      ||           x       x  x           xx            oxx               o  x ",                                               
   "       x  x     xxxxxxxxxxxxxxxx          x          xx            oxx                o  x ",                                               
   "       x  x                               x          xxx          oxx                    x ",                                               
   " xxxxxxx  xxxx                            x            xx        xxxxxxxxxxx             x ",                                               
   " x||||||     x                 x       x  xxx           xx e               x             x ",                                               
   " x           xxxx              x!!   !!x  x              xx    o           x=            x ",                                               
   " x      xxxx x  x              xx!   !xx  xo        x     xxxxxoxxxxxxxxxxxx=            x ",                                               
   "   ooo       x  xxxx            xx o xx   x         xx o      x         |||x               ",                                               
   "             x     x     o       xxoxx    xxx   x    xx      xx            x               ",                                               
   "  xxxxxxxxxxxx     x              xvx     x    ox     xx o  xxxxxx         x               ",                                        
   "     v     v       x    xxx               x     x      xx       xxxxxxx    x        x p  x ",                                               
   "                                          x   xxx       xx o               x        x o  x ",                   
   "                                          x              xx                x        x o  x ",
   "xxxx   xxx   xxxx               xxx xxx   xo              xxxxxxxxxxxxxxxxxx        xxxxxx ",
   "x!!!! !!!!! !!!!x                         x                                                ",
   "x!!!! !!!!! !!!!x                         xxx                                              ",
   "xxxxx xxxxx xxxxx                                                                          ",
   "                                                                                           ",
   "                     xx                          xx                                        ",
   "                     x        =     =     =       x                                        ",
   "                     x      o       e      o      x                                        ",
   "                     x                            x                                        ",
   "                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                                                                                           "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "oo      oo  ooo    oo      oo           ",
   " oo    oo  ooooo   oo      oo           ",
   "  oo  oo  oo   oo  oo      oo           ",
   "   oooo  oo     oo oo      oo           ",
   "    oo   oo     oo oo      oo           ",
   "    oo   oox @ xoo oo      oo           ",
   "    oo    ooxxxoo   oo    oo            ",
   "    oo     ooooo     oooooo             ",
   "    oo      ooo       oooo              ",
   "                                        ",
   "oo    o    oo  oo  ooo     oo           ",                                                                                       
   "oo   ooo   oo  oo  ooo     oo           ",                                                                                        
   "oo  ooooo  oo  oo  oooo    oo           ",                                                                                      
   " oo oo oo oo   oo  oo oo   oo           ", 
   " oo oo oo oo   oo  oo  oo  oo           ",    
   " oo oo oo oo   oo  oo   oo oo           ",         
   "  ooo   ooo    oo  oo    oooo           ",      
   "  ooo   ooo    oo  oo     ooo           ",   
   "   o     o     oo  oo     ooo           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

   ];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
